### ISSUE TITLE
configure scripts searching pf_ring.h and not pfring.h when configuring daq

### ISSUE THREAD

**Issue by tlaurion** [xrl/pf_ring#1]
I had a hard time yesterday finding what the issue was since the configure script refused to configure DAQ to take pfring into account.

The problem was simple but the configure script output was wrong.

To reproduce the output, simply remove /usr/include/linux/pf_ring.h:
in: ./PF_RING/userland/snort/daq-0.5
[./configure]
checking pfring.h usability... no
checking pfring.h presence... no
checking for pfring.h... no

[result]
Build AFPacket DAQ module.. : yes
Build Dump DAQ module...... : yes
Build IPFW DAQ module...... : yes
Build IPQ DAQ module....... : no
Build NFQ DAQ module....... : no
Build PCAP DAQ module...... : yes
Build PF_RING DAQ module... : no

copy back ./PF_RING/kernel/linux/pf_ring.h into /usr/include/linux and the output shows the difference:
[./configure]
checking pfring.h usability... yes
checking pfring.h presence... yes
checking for pfring.h... yes

[result]

Build AFPacket DAQ module.. : yes
Build Dump DAQ module...... : yes
Build IPFW DAQ module...... : yes
Build IPQ DAQ module....... : no
Build NFQ DAQ module....... : no
Build PCAP DAQ module...... : yes
Build PF_RING DAQ module... : yes

So: there is a typo in the output of the configure script which should show pf_ring.h instead of pfring.h!
Keep up the good work,
Thierry Laurion

**Comment by xrl** [comment]
Hmm, I'm not able to reproduce the issue. I have PF_RING installed on my machine and when I did the DAQ's configure it found pf_ring.h AOK.

Let me dig around a little more and get back to you.
